### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by elan** [Kureev/react-native-blur#405]
We see a fair number of these show up in our bug reporting system:

```
java.lang.NullPointerException
Objects.java:220java.util.Objects.requireNonNull	
BlurViewManager.java:35com.cmcewen.blurview.BlurViewManager.createViewInstance	
BlurViewManager.java:20com.cmcewen.blurview.BlurViewManager.createViewInstance	
ViewManager.java:47com.facebook.react.uimanager.ViewManager.createView	
NativeViewHierarchyManager.java:256com.facebook.react.uimanager.NativeViewHierarchyManager.createView	
UIViewOperationQueue.java:200com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute	
UIViewOperationQueue.java:911com.facebook.react.uimanager.UIViewOperationQueue$1.run	
UIViewOperationQueue.java:1025com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches	
UIViewOperationQueue.java:46com.facebook.react.uimanager.UIViewOperationQueue.access$2600	
UIViewOperationQueue.java:983com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded	
GuardedRunnable.java:24com.facebook.react.bridge.GuardedRunnable.run
```

**Comment by Kureev** [comment]
Hi @elan,

Can you provide more information on the topic? For example, a repro would be quite helpful

**Comment by elan** [comment]
Unfortunately I don't have a specific one, except that I've only seen it at launch. Would seem to be a race of some kind.

**Comment by SergioEnrique** [comment]
My app is also crashing in some parts or slowing down when using BlurView on Android when setting the position style to absolute.

I have a HOC for a loader when saving changes on my app, the blur is showed up on the entire screen, most of the times it works well but I have two specific pages in which the blur causes problems, either slowing down the app or crashing it

**Comment by mitjnextt** [comment]
Have anyone resolved it?

**Comment by mitjnextt** [comment]
Have anyone resolved it?

**Comment by mohity777** [comment]
i am facing too. It works for some seconds then crash

**Comment by mrousavy** [comment]
This is a pretty common issue. Apparently Android limits the number of BlurViews per activity to 1, this is a limitation of the eightbitlab.com.blurview.BlurView library.

So if you have multiple `<BlurView />` views per screen, your app will crash on Android.

**Comment by hackrx** [comment]
@mrousavy you are right, I am rendering a list of images in Flatlist and using `BlurView` for each image, and then the app is simply crashing, I think it is only supporting a single blur/screen,

**Comment by bartzy** [comment]
@mrousavy @Kureev 
Did you perhaps find a solution for this issue on Android?

**Comment by nhannah** [comment]
Look like a fix was made on the library: https://github.com/Dimezis/BlurView/issues/110#issuecomment-786939860

**Comment by C-odes** [comment]
> @mrousavy you are right, I am rendering a list of images in Flatlist and using `BlurView` for each image, and then the app is simply crashing, I think it is only supporting a single blur/screen,

Images have a property called blurRadius that you can use. This library is needed to get Views to be blurred so maybe you dont need it .

**Comment by RodolfoGS** [comment]
I've the same issue `@react-native-community/blur: 3.6.0`
Someone could fix it? Thanks

```
java.lang.NullPointerException: null
    at java.util.Objects.requireNonNull(Objects.java:203)
    at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java:35)
    at com.cmcewen.blurview.BlurViewManager.createViewInstance(BlurViewManager.java:20)
    at com.facebook.react.uimanager.ViewManager.createViewInstance(ViewManager.java:139)
    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:83)
    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:261)
    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:186)
    at com.facebook.react.uimanager.UIViewOperationQueue$1.run(UIViewOperationQueue.java:911)
    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:1028)
    at com.facebook.react.uimanager.UIViewOperationQueue.access$2600(UIViewOperationQueue.java:48)
    at com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded(UIViewOperationQueue.java:986)
    at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:31)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6788)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
```

**Comment by RodolfoGS** [comment]
Fix: https://github.com/Kureev/react-native-blur/pull/411

**Comment by FenaliEnacton** [comment]
I have the same issue then I simple decrease the opacity of the component which I want to make blur and give background color transparent 
backgroundColor : (rgba(60, 60, 60, 0.5))

**Comment by zholmes1** [comment]
I am getting the NullPointerException as well. I'm only ever rendering one BlurView. It is positioned absolutely.

**Comment by jellyfish-tom** [comment]
we also are getting this error in our project. But still exists

**Comment by enestatli** [comment]
it is solved by with the version `3.6.1` but not published on npm, add following to your package.json:

"@react-native-community/blur": "https://github.com/Kureev/react-native-blur/archive/refs/tags/v3.6.1.tar.gz",

**Comment by valeriashpiner** [comment]
@Kureev any ideas when 3.6.1 will be published on npm? Thank you!

**Comment by mynameisguy** [comment]
> > Fix: #411
> 
> This does not fix this issue, the crash is happens when the app is in background.
> 
> This probably fixes this issue:
> 
> #399

This doesn't fix it as well.

**Comment by sayurimizuguchi** [comment]
Any timeline when we're going to release/publish 3.6.1?

**Comment by Harisene** [comment]
yep. Crashing on Android 11 for me too...

**Comment by praisedavid787** [comment]
Hi guys, this just came up on my crashlytics too. Anything close to a solution in the works?

Exception java.lang.NullPointerException:
  at java.util.Objects.requireNonNull (Objects.java:220)
  at com.reactnativecommunity.blurview.BlurViewManagerImpl.createViewInstance

**Comment by RnbWd** [comment]
Same I just started seeing this error after upgrading to the latest version

**Comment by Harisene** [comment]
When this will be resolved? I'm having **v4.3.0** of the package. Still crashes rising up...

**Comment by Juan2662** [comment]
Same here. v4.3.0

**Comment by LouisKraemer** [comment]
Same here, latest 4.3.2. Any way I can help (provide logs, other informations)?

**Comment by antseburova** [comment]
I created a patch for v4.3.2 based on this PR and it worked like magic: [https://github.com/Kureev/react-native-blur/pull/399](https://github.com/Kureev/react-native-blur/pull/399). We have applied the patch almost a month ago, and no issues reported since then.

Here is my patch file: [@react-native-community+blur+4.3.2.patch](https://github.com/Kureev/react-native-blur/files/12081335/%40react-native-community%2Bblur%2B4.3.2.patch)

**Comment by sebas21** [comment]
> I created a patch for v4.3.2 based on [this PR](https://github.com/Kureev/react-native-blur/pull/399) and it worked like magic. We have applied the patch almost a month ago, and no issues reported since then.
> 
> Here is my patch file: [@react-native-community+blur+4.3.2.patch](https://github.com/Kureev/react-native-blur/files/12081335/%40react-native-community%2Bblur%2B4.3.2.patch)

@antseburova @dualism98 Can you explain to me how I can make the patch? plz

**Comment by dualism98** [comment]
Hey, @sebas21. You need use this package for patches - https://www.npmjs.com/package/patch-package

**Comment by sebas21** [comment]
> https://www.npmjs.com/package/patch-package

hi @dualism98 , It is that the patch deletes some methods, right? Look how the file turned out:

package com.reactnativecommunity.blurview;

import android.app.Activity;
import android.view.View;
import com.facebook.react.uimanager.ThemedReactContext;

import eightbitlab.com.blurview.BlurView;

import javax.annotation.Nonnull;

@SuppressWarnings("unused")
class BlurViewManagerImpl {

  public static final String REACT_CLASS = "AndroidBlurView";

  public static final int defaultRadius = 10;
  public static final int defaultSampling = 10;

  public static @Nonnull BlurView createViewInstance(@Nonnull ThemedReactContext ctx) {
    BlurView blurView = new BlurView(ctx);
     Activity currentActivity = ctx.getCurrentActivity();
    if (currentActivity != null) {
      View decorView = currentActivity.getWindow().getDecorView();
      blurView
        .setupWith(decorView.findViewById(android.R.id.content))
        .setFrameClearDrawable(decorView.getBackground())
        .setBlurRadius(defaultRadius);
    }
    return blurView;
  }

  public static void setRadius(BlurView view, int radius) {
    view.setBlurRadius(radius);
    view.invalidate();
  }

  public static void setColor(BlurView view, int color) {
    view.setOverlayColor(color);
    view.invalidate();
  }

  public static void setDownsampleFactor(BlurView view, int factor) {}

  public static void setAutoUpdate(BlurView view, boolean autoUpdate) {
    view.setBlurAutoUpdate(autoUpdate);
    view.invalidate();
  }

  public static void setBlurEnabled(BlurView view, boolean enabled) {
    view.setBlurEnabled(enabled);
  }
}


¿All Right?

**Comment by dualism98** [comment]
@sebas21. It looks like he doesn't delete the methods, but changes the create View Instance method, adding a null check so that there is no crash

**Comment by elgambet** [comment]
Still having this problem, it only happens on prod for some devices, receive the following tracktrace on crashlytics:

```
java.util.Objects.requireNonNull (Objects.java:207)
com.reactnativecommunity.blurview.BlurViewManagerImpl.createViewInstance (BlurViewManagerImpl.java:22)
com.reactnativecommunity.blurview.BlurViewManager.createViewInstance (BlurViewManager.java:22)
com.reactnativecommunity.blurview.BlurViewManager.createViewInstance (BlurViewManager.java:12)
com.facebook.react.uimanager.ViewManager.createViewInstance (ViewManager.java:183)
com.facebook.react.uimanager.ViewManager.createView (ViewManager.java:115)
com.facebook.react.uimanager.NativeViewHierarchyManager.createView (NativeViewHierarchyManager.java:281)
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java:194)
com.facebook.react.uimanager.UIViewOperationQueue$1.run (UIViewOperationQueue.java:909)
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches (UIViewOperationQueue.java:1026)
com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded (UIViewOperationQueue.java:984)
com.facebook.react.bridge.GuardedRunnable.run (GuardedRunnable.java:30)
android.os.Handler.handleCallback (Handler.java:984)
android.os.Handler.dispatchMessage (Handler.java:104)
android.os.Looper.loopOnce (Looper.java:238)
android.os.Looper.loop (Looper.java:357)
android.app.ActivityThread.main (ActivityThread.java:8088)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:957)
```

Using:

```
"@react-native-community/blur": "^4.4.0",
"react-native": "0.72.5",
```

**Comment by truongnguyen3** [comment]
Same as @elgambet, I have this problem too, only happens on prod for some devices.
here's the error in Appcenter Crashlytics
```
java.util.Objects.requireNonNull Objects.java:207
com.reactnativecommunity.blurview.BlurViewManagerImpl.createViewInstance BlurViewManagerImpl.java:22
com.reactnativecommunity.blurview.BlurViewManager.createViewInstance BlurViewManager.java:22
com.reactnativecommunity.blurview.BlurViewManager.createViewInstance BlurViewManager.java:12
com.facebook.react.uimanager.ViewManager.createViewInstance ViewManager.java:183
com.facebook.react.uimanager.ViewManager.createView ViewManager.java:115
com.facebook.react.uimanager.NativeViewHierarchyManager.createView NativeViewHierarchyManager.java:281
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute UIViewOperationQueue.java:194
com.facebook.react.uimanager.UIViewOperationQueue$1.run UIViewOperationQueue.java:909
com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches UIViewOperationQueue.java:1026
com.facebook.react.uimanager.UIViewOperationQueue.access$2600 UIViewOperationQueue.java:47
com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded UIViewOperationQueue.java:984
com.facebook.react.bridge.GuardedRunnable.run GuardedRunnable.java:30
android.os.Handler.handleCallback Handler.java:942

```

Using:
```
"@react-native-community/blur": "^4.4.0",
"react-native": "0.72.15",
```

**Comment by Nader-CS** [comment]
same issue

**Comment by BrandonCao** [comment]
Same issue

**Comment by Essam-Harrous** [comment]
same issue on PlayStore review.
I'm gonna delete this library for now

**Comment by apinedo-sbpay** [comment]
Having this issue. Read in another comment that it might have to do with having multiple instances of a BlurView at the same time. Has this been confirmed to be the case? 

im running version 4.4.1. 

@Essam-Harrous any alternatives ?

**Comment by nhannah** [comment]
I remember working around this years ago by avoiding multiple instances. But you may want to consider react native skia now for this.

**Comment by MadeinFrance** [comment]
@nhannah have you considered `expo-blur`? Regarding the bundle size it's a lighter solution.

**Comment by nhannah** [comment]
The project I used this on I have not been a part of for many years, so have not had a need. Thanks for the insight though.
