### ISSUE TITLE
[Android] Crash on screen navigation

### ISSUE THREAD

**Issue by TommysG** [Kureev/react-native-blur#461]
The app is crashing without error when i add the BlurView component in my stack screen.

### Workaround

```js
<Stack.Navigator screenOptions={{animationEnabled: false}}>
  ...
  ...
</Stack.Navigator>
```

But i don't have the nice transitions between the screens.

Any solution for this?

### Versions
"@react-navigation/native": "^6.0.8",
"@react-navigation/stack": "^6.1.1"
"@react-native-community/blur": "^3.6.0"

**Comment by TommysG** [comment]
Update!!!

The problem is not with navigation Stack it's when using bottom Tabs. I placed the screen with the blurview out of the Bottom Tabs, in my initial Stack Screen and it's working fine.

The order of my Stack/Tabs is like this:

```
-- Initial Stack
    -- Tabs Navigator 
       - Screen 1
       - Screen 2
       - ...
    -- Stack
       - Screen 1 with blur
       - Screen 2 with blur
       - ...
```

**Comment by star-heng** [comment]
same problem

**Comment by YunsGeek** [comment]
same here !

**Comment by mjm918** [comment]
Hi everyone, I provided a reproduction of this issue in react-navigation repo. It seems the author is not responding.

If you comment in that issue, I think it will catch the attention of the author. The issue link : https://github.com/software-mansion/react-native-screens/issues/1287#issuecomment-1074883686

**Comment by JiSikKim** [comment]
Same problem

**Comment by Josiahhenry23** [comment]
Same Problem Here.

**Comment by idrissakhi** [comment]
i have re-written the lib to work correctly on new RN version => https://www.npmjs.com/package/rn-id-blurview
need some support so the react community take it to replace this package that seems to not be maintained anymore

**Comment by TommysG** [comment]
> i have re-written the lib to work correctly on new RN version => https://www.npmjs.com/package/rn-id-blurview need some support so the react community take it to replace this package that seems to not be maintained anymore

On Android i'm still getting this Exception while using it inside a StackScreen  which is wrapped inside BottomTabs and i'm navigating from ScreenA to ScreenB inside the StackScreen.


```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0

FATAL EXCEPTION: main
Process: com.awesometsproject, PID: 9847
java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at android.view.ViewGroup.getAndVerifyPreorderedView(ViewGroup.java:3659)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4147)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
	at android.view.View.draw(View.java:21293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:772)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:744)
	at android.view.View.draw(View.java:21424)
	at android.view.View.draw(View.java:21295)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:226)
	at android.view.View.draw(View.java:21293)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4388)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4149)
	at android.view.View.draw(View.java:21424)
	at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:113)
	at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:53)
	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1088)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2745)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1721)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7598)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:966)
	at android.view.Choreographer.doCallbacks(Choreographer.java:790)
	at android.view.Choreographer.doFrame(Choreographer.java:725)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by mjm918** [comment]
> java.lang.IndexOutOfBoundsException

Hi @TommysG last time we found out that the crash happens because of the Android BlurView & also because of react-native-screens. There was a PR to fix the issue in react-native-screens which can be found [here](https://github.com/software-mansion/react-native-screens/issues/1287#issuecomment-1097911027) . Use this PR to fix the issue. 

I checked the repo of @idrissakhi and noticed that the repo is using the latest version of BlurView. So I think it should solve your crash issue

**Comment by aaly00** [comment]
I can confirm that @idrissakhi fork didn't work for me.

**Comment by devin989** [comment]
Same here !

**Comment by ZaidQ797** [comment]
I have the same issue but This is cuz of position absolute in style.But if you remove that then blurView is not visible

**Comment by chenop** [comment]
This [patch](https://gist.github.com/artyorsh/cb8cf71a28be5ccde8f1926e06dbe3a8) helped me to resolve this issue.

**Comment by samvoults** [comment]
The problem disappear when I remove the animation on the stack navigator from react-navigation/native-stack :

```
import { createNativeStackNavigator } from "@react-navigation/native-stack";

const HomeStack = createNativeStackNavigator();

export default function PartiesNavigator() {
  return (
    <HomeStack.Navigator
      initialRouteName="HomeStack"
      screenOptions={{
        presentation: "card",
        animation: "none", // <=====  I ADDED THIS LINE
      }}
    >
      <HomeStack.Screen
        name="Homescreen"
        component={Homescreen}
      />

      <HomeStack.Screen // <=====  THIS IS THE SCREEN USING THE BLURVIEW 
        name="ScreenUsingBlurView"
        component={ScreenUsingBlurView}
      />
    </HomeStack.Navigator>
  );
}
```

It's still not a fix as I would like to have the default card animation on Android.

**Comment by leil309** [comment]
good

**Comment by archidigital** [comment]
I've tested and the issue was fixed
---
@react-native-community/blur: 4.3.2
@react-navigation: v6

**Comment by zahid502** [comment]
I'm facing the same issue, not fixed for me.

**Comment by MarcusDelvecchio** [comment]
Also facing the same issue and unable to resolve by removing navigation animations.

**Comment by SOONAIN3** [comment]
> Reference in new iss

thx it works

**Comment by zero19124** [comment]
> The problem disappear when I remove the animation on the stack navigator from react-navigation/native-stack :
> 
> ```
> import { createNativeStackNavigator } from "@react-navigation/native-stack";
> 
> const HomeStack = createNativeStackNavigator();
> 
> export default function PartiesNavigator() {
>   return (
>     <HomeStack.Navigator
>       initialRouteName="HomeStack"
>       screenOptions={{
>         presentation: "card",
>         animation: "none", // <=====  I ADDED THIS LINE
>       }}
>     >
>       <HomeStack.Screen
>         name="Homescreen"
>         component={Homescreen}
>       />
> 
>       <HomeStack.Screen // <=====  THIS IS THE SCREEN USING THE BLURVIEW 
>         name="ScreenUsingBlurView"
>         component={ScreenUsingBlurView}
>       />
>     </HomeStack.Navigator>
>   );
> }
> ```
> 
> It's still not a fix as I would like to have the default card animation on Android.

thx it works
