### ISSUE TITLE
drawRenderNode error

### ISSUE THREAD

**Issue by Bayramito** [Kureev/react-native-blur#509]
the library conflicts with react navigation 6.

its crashing with drawRenderNode is not supported.

as i mentioned here
https://github.com/Kureev/react-native-blur/issues/489#issuecomment-1315855648

do you planning to fix that soon ?

**Comment by MarianLudwig** [comment]
Facing the same issue on my android device

**Comment by Bayramito** [comment]
Its a device specific thing i believe becausw i testes same exact apk on different device  and it did work.
On Relme  doesnt work on me

**Comment by jonathanroze** [comment]
Same thing for me on a Pixel 6 emulator on Android 13

**Comment by MoronovArt** [comment]
Same Issue

**Comment by jspizziri** [comment]
@Bayramito @MoronovArt @jonathanroze 

The following [commit fixed this issue for me](https://github.com/bobvanratingen/react-native-blur/pull/1/files). It's not released yet so you could fix your issue locally with `patch-package`.

**Comment by vinitraj10** [comment]
Not sure if it is still relevant to you all, since we had the same issue and as we work closely with CI/CD, applying patch locally was not a good solution for us, as CI scripts need to be updated to discard the changes every time `yarn` or `npm install` done.

Instead i just moved the patch bundle into a github fork and started using it in our package.json which was much more cleaner solution as it doesn't touch `.gitignore` to ignore few patch files and CI is also happy.

> just forking to git repo and using url might not work as the package is not compiled while forked so you need to bundle it and place in fork if you want to use it that way

You can use our bundle by using the following command

```js
> yarn add 'vinitraj10/react-native-blur'
```
or
```js
npm install 'vinitraj10/react-native-blur'
```

**Comment by Bayramito** [comment]
> Not sure if it is still relevant to you all, since we had the same issue and as we work closely with CI/CD, applying patch locally was not a good solution for us, as CI scripts need to be updated to discard the changes every time `yarn` or `npm install` done.
> 
> Instead i just moved the patch bundle into a github fork and started using it in our package.json which was much more cleaner solution as it doesn't touch `.gitignore` to ignore few patch files and CI is also happy.
> 
> > just forking to git repo and using url might not work as the package is not compiled while forked so you need to bundle it and place in fork if you want to use it that way
> 
> You can use our bundle by using the following command
> 
> ```js
> > yarn add 'vinitraj10/react-native-blur'
> ```
> 
> or
> 
> ```js
> npm install 'vinitraj10/react-native-blur'
> ```

there is no such package on npm

**Comment by vinitraj10** [comment]
@Bayramito Yes this package is not published on npm registry, that is why it's just using github servers to pull that library code, it was generated from my repository which is hosted [here](https://github.com/vinitraj10/react-native-blur) and using https://gitpkg.vercel.app/ to generate a proxy npm package using git repository

**Comment by ZanaNabaz** [comment]
Im facing the same issue, using react-native navigation 5.x, if im showing blurview and use "nav.GoBack()" it will crash the app with the following error :

ADB: 

>  java.lang.IllegalArgumentException: Software rendering doesn't support drawRenderNode
                                                                                                    	at android.graphics.Canvas.drawRenderNode(Canvas.java:2316)
                                                                                                    	at eightbitlab.com.blurview.RenderEffectBlur.render(RenderEffectBlur.java:68)
                                                                                                    	at eightbitlab.com.blurview.PreDrawBlurController.draw(PreDrawBlurController.java:159)
                                                                                                    	at eightbitlab.com.blurview.BlurView.draw(BlurView.java:52)
                                                                                                    	at android.view.View.draw(View.java:24278)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at android.view.View.draw(View.java:24409)
                                                                                                    	at android.widget.ScrollView.draw(ScrollView.java:2850)
                                                                                                    	at com.facebook.react.views.scroll.ReactScrollView.draw(ReactScrollView.java:519)
                                                                                                    	at android.view.View.draw(View.java:24278)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
                                                                                                    	at android.view.View.draw(View.java:24409)
                                                                                                    	at android.view.View.draw(View.java:24278)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at android.view.View.buildDrawingCacheImpl(View.java:23658)
                                                                                                    	at android.view.View.buildDrawingCache(View.java:23524)
                                                                                                    	at android.view.View.draw(View.java:24128)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:743)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
                                                                                                    	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4505)
                                                                                                    	at android.view.View.draw(View.java:24276)
                                                                                                    	at android.view.ViewGroup.drawChild(ViewGroup.java:4748)
