### ISSUE TITLE
I got this error

### ISSUE THREAD

**Issue by scott8013** [Kureev/react-native-blur#530]
yarn android
yarn run v1.22.19
$ react-native run-android
info JS server already running.
info Installing the app...

> Configure project :app
Reading env from: .env
5 actionable tasks: 5 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-community_blur:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-community_blur:debugCompileClasspath'.
   > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
     Required by:
         project :react-native-community_blur
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://www.jitpack.io/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://jitpack.io/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 20s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':react-native-community_blur:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':react-native-community_blur:debugCompileClasspath'.
   > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
     Required by:
         project :react-native-community_blur
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://www.jitpack.io/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://repo.maven.apache.org/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused
      > Could not resolve com.github.Dimezis:BlurView:version-2.0.2.
         > Could not get resource 'https://jitpack.io/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
            > Could not GET 'https://jitpack.io/com/github/Dimezis/BlurView/version-2.0.2/BlurView-version-2.0.2.pom'.
               > Connect to 127.0.0.1:7890 [/127.0.0.1] failed: Connection refused

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 20s

    at makeError (/Users/dendi/Desktop/works/react.native/listenbook/node_modules/execa/index.js:174:9)
    at /Users/dendi/Desktop/works/react.native/listenbook/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/dendi/Desktop/works/react.native/listenbook/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/dendi/Desktop/works/react.native/listenbook/node_modules/@react-native-community/cli/build/index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by CodingWithNobody** [comment]
https://www.youtube.com/watch?v=qSlnZHPFxfk this will help
