### ISSUE TITLE
Trouble building with newArchEnabled on Android

### ISSUE THREAD

**Issue by jcarioti** [Kureev/react-native-blur#566]
After trying to enable the new fabric architecture, I'm seeing this build failure: `> Task :react-native-community_blur:generateCodegenSchemaFromJavaScript FAILED`

The stack trace looks like this: 
```
node:internal/fs/utils:347
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat 'android'
    at Object.lstatSync (node:fs:1574:3)
    at /Users/joe/Development/apex-fusion/fusion-react-native/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js:75:10
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/joe/Development/apex-fusion/fusion-react-native/node_modules/react-native-codegen/lib/cli/combine/combine-js-to-schema-cli.js:74:10)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'lstat',
  code: 'ENOENT',
  path: 'android'
}

Node.js v18.14.2
```

RN: 0.71.11
Blur: 4.3.2

Anyone have any leads as to what's going on? I don't see anything similar in the the reported issues.

**Comment by recumbentseeker** [comment]
We solved this by upgrading  "react-native-codegen" to "0.71.5".

**Comment by jcarioti** [comment]
> We solved this by upgrading "react-native-codegen" to "0.71.5".

That solved it, thank you!
